export default games;

let games = [
    {
        id : 0,
        name : "Gloomhaven",
        age : 14,
        category : ["adventure", "dice"],
        image : "asset/image/gloomhaven.webp"
    },
    {
        id : 1,
        name : "Happy Salmon",
        age : 6,
        category : ["card", "education"],
        image : "asset/image/happy_salmon.webp"
    },
    {
        id : 2,
        name : "Azul summer pavillion",
        age : 8,
        category : ["puzzle"],
        image : "asset/image/azul.webp"
    },
    {
        id : 3,
        name : "Catan",
        age :10,
        category : ["logique", "dice"],
        image : "asset/image/catan.webp",
    },
    {
        id : 4,
        name : "Lanterns",
        age : 8,
        category : ["puzzle"],
        image : "asset/image/lanterns.webp",
    },
    {
        id : 5,
        name : "Twin it",
        age : 6,
        category : ["card"],
        image : "asset/image/twin_it.webp",
    },
    {
        id : 6,
        name : "Junk orbit",
        age : 10,
        category : ["logique"],
        image : "asset/image/junk_orbit.webp",
    },
    {
        id : 7,
        name : "Exit: house of riddles",
        age : 10,
        category : ["logique"],
        image : "asset/image/exit.webp",
    },
    {
        id : 8,
        name : "Clank! in space",
        age : 12,
        category : ["adventure"],
        image : "asset/image/clank.webp",
    },
    {
        id : 9,
        name : "Comanauts",
        age : 14,
        category : ["adventure"],
        image : "asset/image/comanauts.webp",
    },
    {
        id : 10,
        name : "Asking for trobils",
        age : 12,
        category : ["logique"],
        image : "asset/image/asking_for_trobils.webp",
    },
    {
        id : 11,
        name : "Urbania",
        age : 10,
        category : ["dice", "logique"],
        image : "asset/image/urbania.webp",
    },
    {
        id : 12,
        name : "Neon gods",
        age : 14,
        category : ["dice"],
        image : "asset/image/neon_gods.webp",
    },
    {
        id : 13,
        name : "Kingdom builder",
        age : 8,
        category : ["logique"],
        image : "asset/image/kingdom_builder.webp",
    },
    {
        id : 14,
        name : "Architects of the west kingdom",
        age : 12,
        category : ["logique"],
        image : "asset/image/architects_of_the_west_kingdom.webp",
    },
    {
        id : 15,
        name : "7 wonders",
        age : 10,
        category : ["card"],
        image : "asset/image/7_wonders.webp",
    },
    {
        id : 16,
        name : "Volt",
        age : 10,
        category : ["adventure"],
        image : "asset/image/volt.webp",
    },
    {
        id : 17,
        name : "Emira",
        age : 12,
        category : ["logique"],
        image : "asset/image/emira.webp",
    },
    {
        id : 18,
        name : "Dream catchers",
        age : 4,
        category : ["education"],
        image : "asset/image/dream_catcher.webp",
    },
    {
        id : 19,
        name : "The expanse",
        age : 14,
        category : ["logique"],
        image : "asset/image/the_expanse.webp",
    },
    {
        id : 20,
        name : "Wendake",
        age : 14,
        category : ["logique"],
        image : "asset/image/wendake.webp",
    },
    {
        id : 21,
        name : "Cortex challenge",
        age : 8,
        category : ["education"],
        image : "asset/image/cortex.webp",
    },
    {
        id : 22,
        name : "Rat a tat cat",
        age : 6,
        category : ["card"],
        image : "asset/image/rat_a_tat_cat.webp",
    },
    {
        id : 23,
        name : "Bardagi",
        age : 10,
        category : ["adventure"],
        image : "asset/image/bardagi.webp",
    },
    {
        id : 24,
        name : "Pucket",
        age : 4,
        category : ["education"],
        image : "asset/image/pucket.webp",
    },
    {
        id : 25,
        name : "Duelosaur island",
        age : 10,
        category : ["card"],
        image : "asset/image/duelosaur.webp",
    },
    {
        id : 26,
        name : "D-Day dice",
        age : 14,
        category : ["dice"],
        image : "asset/image/d-day_dice.webp",
    },
    {
        id : 27,
        name : "Doctor panic",
        age : 7,
        category : ["card", "education"],
        image : "asset/image/doctor_panic.webp",
    },
    {
        id : 28,
        name : "D&D: Waterdeep - Dungeon of the Mad Mage",
        age : 14,
        category : ["adventure", "dice"],
        image : "asset/image/DnD_Dungeon-of-the-Mad-Mage.webp",
    },
    {
        id : 29,
        name : "Scorpius freighter",
        age : 14,
        category : ["logique"],
        image : "asset/image/scorpius_freighter.webp",
    },
]